name: specific_commit

on:
  schedule:
    #runs the workflow every Monday at midnight.
    - cron: '0 0 * * MON' 
  push:
    branches:
      - main
    paths: 
      - ./
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 28222cff1015d76dba6ead5a871face4a10f7a5b
    - name: cat file 
      run: |
        cat .github/workflows/MURaM_build.yaml
  
      
      
      
      
      
      
      
